services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_URL=${DB_URL}
    volumes:
      - /app/node_modules
    restart: unless-stopped
